project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "premiere/*/*.ipynb"

website:
  title: "NSI"
  navbar:
    left:
      - text: "Première"
        menu:
          - text: "IHM"
            href: premiere/ihm/index.ipynb
          - text: "Intro python"
            href: premiere/intro_python/index.ipynb


  sidebar:

    - title: "IHM"
      contents:
        - premiere/ihm/index.ipynb
        - premiere/ihm/fiche.ipynb
    
    - title: "Intro python"
      contents:
        - premiere/intro_python/index.ipynb
        - premiere/intro_python/variables.ipynb


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <script src="https://cdn.jsdelivr.net/npm/thebe@latest/lib/index.js"></script>
          <script src="https://cdn.jsdelivr.net/npm/@jupyterlite/javascript-kernel@0.4.0/dist/index.js"></script>
    include-after-body:
      - text: |
          <script src="/js/thebe_config.js"></script>
          <script src="/js/thebe_init.js"></script>



